//import java.util.Random;
import java.util.*;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int t = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.


			double totalSum = 0.0;
			double average = 0.0;

			boolean boyWasBorn = false;//1
			boolean girlWasBorn = false;//0
			int childrenCounter = 1; //should be 1 though

			int twoChildrenFam = 0;
			int threeChildrenFam = 0;
			int fourChildrenFam = 0;

			int sexIndicator = (int) (generator.nextDouble() *2);

			if (sexIndicator == 1) {

				boyWasBorn = true;
			}

			else
			{

				girlWasBorn = true;

			}





			for (int i = 0; i < t   ;  i ++) {

				while (boyWasBorn != girlWasBorn )
				{
					sexIndicator = (int) (generator.nextDouble() *2);
					if (sexIndicator == 1)
				 {
					
					boyWasBorn = true;
					
					}
					

					else
						{
						
							girlWasBorn = true;


						}
				childrenCounter ++;
				}

				if ( childrenCounter == 2){

					twoChildrenFam++;

				}

				else {

					if (childrenCounter == 3){

						threeChildrenFam++;

					}
					else 
						fourChildrenFam++;
				}


				
				totalSum += childrenCounter;
				childrenCounter = 1;
				boyWasBorn = false;
				girlWasBorn = false;

				sexIndicator = (int) (generator.nextDouble() *2);

				if (sexIndicator == 1) {
				
					boyWasBorn = true;
				}

				else
				{
					
					girlWasBorn = true;

				}




				
			}
			average = totalSum/(double)t;

			System.out.println("Average: " + average+ " children to get at least one of each gender.");
			System.out.println("Number of families with 2 children: " + twoChildrenFam);
			System.out.println("Number of families with 3 children: " + threeChildrenFam);
			System.out.println("Number of families with 4 or more children: " + fourChildrenFam);


			if ((twoChildrenFam >= threeChildrenFam) && (twoChildrenFam >=fourChildrenFam)) {

				System.out.println("The most common number of children is 2.");

			}
			else {

					if ( (threeChildrenFam >= twoChildrenFam) && (threeChildrenFam >= fourChildrenFam))
					{
						System.out.println("The most common number of children is 3.");
					}
					else
					{
						System.out.println("The most common number of children is 4 or more.");

					}




			}


		























	}
}
